### ISSUE TITLE
Nationality problem

### ISSUE THREAD

**Issue by voffan** [voffan/abit-anketa#3]
person.nationality = AttrValue.objects.get(pk=10)
or
person.nationality = get_object_or_404(AttrValue, pk=10)

**Comment by st-pi** [comment]
name 'HttpResponseRedirect' is not defined

```
    person.save()
    return HttpResponseRedirect(reverse('application'(ссылка из урла на заявление)))
data={}
context = {'data':data}
context.update(csrf(request))
return render(request,'/',context)
```

Я же определил редирект, чего он жалуется

**Comment by voffan** [comment]
from django.shortcuts import HttpResponseRedirect

**Comment by st-pi** [comment]
NoReverseMatch at /person_add/
Reverse for 'StartApp' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
