### ISSUE TITLE
Запустить проект

### ISSUE THREAD

**Issue by voffan** [voffan/abit-anketa#7]
Разрешить конфликты имен атрибутов классов.

**Comment by st-pi** [comment]
ВОТ ПРОЕКТ НУЖЕН ВСЕМ, А ЗАПУСТИТЬ ТОЛЬКО Я ЕГО ДОЛЖЕН, ГДЕ СПРАВЕДЛИВОСТЬ!?

**Comment by st-pi** [comment]
http://imgur.com/xi247BU
http://imgur.com/3SIs800

**Comment by voffan** [comment]
в первом случае я изменил модельку,
Во-втором случае необходимо syncdb сделать

**Comment by voffan** [comment]
Так что синхронизируйся Андрей

**Comment by st-pi** [comment]
http://i.imgur.com/5wX8UvY.png

**Comment by voffan** [comment]
While migrations are per-app, the tables and relationships implied by your models are too complex to be created for just one app at a time. When you make a migration that requires something else to run - for example, you add a ForeignKey in your books app to your authors app - the resulting migration will contain a dependency on a migration in authors.

т.е. последовательность миграций надо определить

This means that when you run the migrations, the authors migration runs first and creates the table the ForeignKey references, and then the migration that makes the ForeignKey column runs afterwards and creates the constraint. If this didn’t happen, the migration would try to create the ForeignKey column without the table it’s referencing existing and your database would throw an error.

This dependency behavior affects most migration operations where you restrict to a single app. Restricting to a single app (either in makemigrations or migrate) is a best-efforts promise, and not a guarantee; any other apps that need to be used to get dependencies correct will be.

**Comment by 4ino** [comment]
А там папка мигратионс точно нужна ? 
Я пока не переименовал ее маэскуель вообще никак нормально несинхронил 
Там столбцы лишние 
левые классы или вообще не создавал класс короче говоря я хз прост заного создал таблицы
